/**
 * glossary.ts — the teaching layer for progressive disclosure.
 *
 * One consistent RESTAURANT analogy runs through every entry (see docs/learn.md):
 *   front counter = the pages people see · kitchen = the working back end ·
 *   doors = endpoints · security guard = middleware · filing cabinets = database
 *   tables · recipe book = schema · pantry suppliers = dependencies · sticky
 *   notes with door codes = environment variables · order tickets = requests.
 *
 * Each concept gives a non-coder a friendly name, the real technical word, a
 * two-sentence plain definition, a one-sentence "why a builder should care", and
 * the shared analogy. The app renders these in the learn popover and the
 * "Learn more" panel; nothing here is generated by an LLM.
 */
export interface Concept {
  key: string;
  /** Friendly, non-technical name. */
  friendly: string;
  /** The real technical term. */
  technical: string;
  /** ≤ 2 sentences, plain English. */
  plain: string;
  /** One sentence: why a builder should care. */
  why: string;
  /** The restaurant analogy for this concept. */
  analogy: string;
}

export const GLOSSARY: Concept[] = [
  {
    key: 'page',
    friendly: 'Page',
    technical: 'page / frontend route',
    plain:
      'A page is a screen people actually see and tap on in your app. It’s the part of your app a visitor looks at.',
    why: 'Pages are where your users meet your product, so they decide the first impression.',
    analogy: 'The front counter of the restaurant — where customers walk up and place an order.',
  },
  {
    key: 'endpoint',
    friendly: 'Endpoint',
    technical: 'route / API endpoint',
    plain:
      'An endpoint is a doorway that other software uses to talk to your app. A page sends a message to an endpoint to get something done.',
    why: 'Endpoints are the contract between your screens and your logic — if one is missing, a feature silently breaks.',
    analogy: 'A door into the kitchen — each one takes a specific kind of order ticket.',
  },
  {
    key: 'guard',
    friendly: 'Security guard',
    technical: 'middleware',
    plain:
      'A guard is code that runs before a request is allowed through, to check things like “are you logged in?”. It stands in front of an endpoint.',
    why: 'A guard is how you keep the wrong people out of the right doors, so confirming it’s really attached matters.',
    analogy: 'The doorkeeper who checks every ticket before letting it reach the kitchen.',
  },
  {
    key: 'records',
    friendly: 'Records',
    technical: 'database table',
    plain:
      'Records are where your app remembers information, like a list of users or orders. Each table holds one kind of thing.',
    why: 'Records are your app’s long-term memory — losing or mis-shaping them is the costliest kind of mistake.',
    analogy: 'A filing cabinet in the back — one drawer for customers, one for orders.',
  },
  {
    key: 'settings-secrets',
    friendly: 'Settings & secrets',
    technical: 'environment variables',
    plain:
      'These are values your app reads at startup, like passwords and keys, kept outside the code. They change per machine without editing the app.',
    why: 'Secrets in the wrong place leak; knowing which ones your code reads is a security basic.',
    analogy: 'Sticky notes with the door codes — kept by the manager, never printed on the menu.',
  },
  {
    key: 'building-blocks',
    friendly: 'Building blocks',
    technical: 'dependencies',
    plain:
      'These are ready-made pieces of other people’s code your app uses so you don’t rebuild everything. You install them and call them.',
    why: 'Every block you add is code you didn’t write but still ship, so it’s worth knowing what’s in there.',
    analogy: 'Outside suppliers who deliver pantry ingredients you didn’t grow yourself.',
  },
  {
    key: 'front-vs-kitchen',
    friendly: 'Front counter vs kitchen',
    technical: 'frontend vs backend',
    plain:
      'The front counter is what people see and touch; the kitchen is the hidden part that does the actual work. They talk through doors.',
    why: 'Most confusing bugs come from a mismatch between what the counter asks for and what the kitchen serves.',
    analogy: 'The dining room versus the kitchen — same restaurant, two very different jobs.',
  },
  {
    key: 'order-ticket',
    friendly: 'Order ticket',
    technical: 'client call / request',
    plain:
      'An order ticket is a single message your page sends asking the back end to do something. The back end reads it and responds.',
    why: 'Tracing the ticket from page to endpoint is how you prove a feature is actually wired up, not just drawn.',
    analogy: 'The slip the counter hands through the door so the kitchen knows what to make.',
  },
  {
    key: 'blueprint',
    friendly: 'Blueprint',
    technical: 'schema',
    plain:
      'A blueprint describes the shape of your records — what fields each thing has. It’s the agreed plan everything else follows.',
    why: 'When the blueprint and the real records drift apart, data quietly corrupts — so the blueprint is worth verifying.',
    analogy: 'The recipe book — every dish (record) has a fixed list of ingredients (fields).',
  },
];

/** Map a FlowStep kind to its glossary concept key. */
export function conceptKeyForStep(kind: string): string | null {
  switch (kind) {
    case 'page':
      return 'page';
    case 'action':
      return 'order-ticket';
    case 'endpoint':
      return 'endpoint';
    case 'guard':
      return 'guard';
    case 'table':
      return 'records';
    default:
      return null;
  }
}
